name: Android CI

on:
  push:
    branches: [ main ]
    paths: 'trackr-app'
  pull_request:
    branches: [ main ]
    paths: 'trackr-app'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      working-directory: 'trackr-app'
      run: chmod +x gradlew
      
    - name: Build with Gradle
      working-directory: 'trackr-app'
      run: ./gradlew build
      
  android_tests:
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v2
      
      - name: Grant execute permission for gradlew
        working-directory: 'trackr-app'
        run: chmod +x gradlew
      
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          script: ./gradlew connectedCheck --stacktrace
          working-directory: 'trackr-app'
